var res = {
    buttonEffet_mp3 : 'res/shoot/shoot.mp3',
    buttonEffet_ogg : 'res/shoot/shoot.ogg',
    buttonEffet_wav : 'res/shoot/shoot.wav',
    flare_jpg : 'res/shoot/flare.jpg',
    hole_effect_png : 'res/shoot/hole_effect.png',
    hole_stencil_png : 'res/shoot/hole_stencil.png',
    girl_jpg:'res/shoot/girl.jpg',
    girl_jpg_1:'res/shoot/girl1.jpg',
    sky_bg:'res/shoot/skybg.jpg',
    tile_map_bg_tmx:'res/shoot/orthogonal-test2.tmx',
    tile_map_bg:'res/shoot/fixed-ortho-test2.png',
    s_cyborg_plist : "res/shoot/cyborg.plist",
    s_cyborg_png : "res/shoot/cyborg.png",
    s_cyborg_xml : "res/shoot/cyborg.xml",
    fire_png:'res/shoot/fire.png',
    jack:'res/Captain_Jack.json',
    loading_png : 'res/loading.jpg',
    menu_png : 'res/menu.png',
    arial_14_fnt : 'res/arial-14.fnt',
    arial_14_png : 'res/arial-14.png',
    sandbg0:'sandbg0.png',
    //-----ccs -----//
    shaq:"res/GeneralShark.json",
    bs:'res/BattleLayer.json',
    sand_tmx:'res/BattleScene/sandbg/sand.tmx',
};

var g_mainmenu = [
    res.loading_png,
    res.menu_png,
];

var g_maingame = [
    res.sandbg0,
    res.hole_stencil_png,
    res.hole_effect_png,
    res.flare_jpg,
    res.sky_bg,
    res.girl_jpg,
    res.girl_jpg_1,
    res.fire_png,
    res.arial_14_png,
    res.arial_14_fnt,
    res.tile_map_bg_tmx,
    res.tile_map_bg,
    res.s_cyborg_xml,
    res.s_cyborg_png,
    res.s_cyborg_plist,
    res.sand_tmx,
    res.jack,
    res.shaq,
    res.bs,
];
